"use client"
import { Container } from "react-bootstrap";
import PpHeader from "../components/ppheader";
import Footer from "../components/footer";
import Copyright from "../components/copyright";
import Link from "next/link";

export default function PrivacyPolicy () {
    const bannerbg = '/img/Solvists-PP-banner.png';
    const headline = 'Privacy Policy';
    return (
        <>
        <PpHeader url={bannerbg} headline={headline} />
        <Container style={{marginTop:'60px',marginBottom:'60px'}}>
            <p>1. <b>BACKGROUND</b></p>
            <ul>
                <li>This document (“<b>PrivacyPolicy</b>”) is an electronic record in terms of: (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
                <li>This Privacy Policy is published in accordance with the Information Technology (Reasonable security practices and procedures and sensitive personal information) Rules, 2011 (“<b>SPI Rules</b>”); and (iii) Regulation 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, that require publishing the privacy policy that is applicable in relation to the access or usage of <b>https://cms.org.in/ website (“Website”)</b>.</li>
                <li>The Website is owned, registered and operated by <b>Catalyst Management Services Private Limited (“Organization”)</b>, a social impact organisation having its place of business at No. 25, Raghavendra Nilaya, AECS Layout, Ashwathnagar, Bangalore – 560 094.</li>
                <li>This Privacy Policy covers: (i) the type of information collected from the Organization through the Website including personal data or information (if any); (ii) the purpose, means and modes of usage of such information; and (iii) how and to whom such information which has been collected will be disclosed.</li>
                <li>For the purpose of this Privacy Policy, wherever the context so requires <b>“You“</b>, <b>“Your”</b> or <b>“User”</b> shall mean any natural or legal person who uses the Website for availing the Services on the Website. The term <b>“We”</b>, <b>“Us”</b>, <b>“Our”</b> shall mean the Organization, its employees, and authorised agents that perform any services on the Organization’s behalf.</li>
            </ul>
            <p>All the other defined terms in this Privacy Policy shall have the meaning ascribed to it in the Organization’s terms of use, which maybe found here.</p>
            <ul>
                <li>We reserve the right to make changes to this Privacy Policy at any time. Any such modification will become effective immediately upon the Organization posting it on the Website and Your continued use of the Website constitutes Your consent to such modifications. You agree to periodically review the current version of the Privacy Policy updated by the Organization. If you do not agree with the terms of the Privacy Policy, please do not use the Website.</li>
                <li>If You choose to use the Website, then you agree to the collection and use of information in relation with this Privacy Policy. The Personal Information that is collected is used for providing and improving the Services availed on the Website.</li>
            </ul>
            <p>2. <b>TYPE OF INFORMATION COLLECTED FROM YOU</b></p>
            <ul>
                <li>“<b>Personal Information</b>” shall have the same meaning as ascribed to it under the SPI Rules.</li>
                <li>When You avail Our services through the Website, we would be collecting the following information from You: (i) Your contact number (mobile/landline); (ii) You Name; (iii) Your postal address; and (iv) any log data Your browser shared with us such as (a) Your Computer’s Internet Protocol (“IP“) address; (b) Browser version; (c) Pages of Our Service that You visit; (d) Time and date of Your visit; (e) Time spent on those pages.</li>
            </ul>
            <p>3. <b>USE OF COLLECTED INFORMATION</b></p>
            <ul>
                <li>The information collected by Us shall be used for the sole purpose of contacting or identifying you.</li>
            </ul>
            <p>4. <b>DISCLOSURE OF INFORMATION COLLECTED ON THE WEBSITE</b></p>
            <ul>
                <li>The Organization does not sell, trade, or rent or disclose Your Personal Information to any third party. However, the Organization cannot fully ensure that such information will not be disclosed to third parties. For example, we may be legally obligated to disclose information to the government or third parties under certain circumstances, third parties may circumvent the Organization’s security measures to unlawfully intercept or access transmissions or private communications, or an error may occur in the Website. In the unlikely event that the Organization needs to investigate or resolve possible problems or inquiries, we may, and you authorize the Organization to, disclose any information about you to government officials as permitted by applicable law.</li>
                <li>We reserve the right to disclose any Personal Information as required by law and when We believe, at Our sole discretion that disclosure is necessary to protect Our rights, protect someone from injury and/or to comply with a judicial proceeding, court order, or legal process served on Our Website.</li>
            </ul>
            <p>5. <b>COOKIES</b></p>
            <ul>
                <li>The Website uses temporary cookies, which are files with small amounts of data that is commonly used as an anonymous unique identifier. These files are sent to Your browser from the website that You visit and are stored on Your computer’s hard drive. The information collected through these cookies is used by Us to collect information, for the technical administration of the Website and to improve the quality of Our services.</li>
                <li>These cookies are intended to be automatically cleared or deleted when the User quits the browser application. You are encouraged to use the “clear cookies” functionality of Your browser to ensure such clearing/deletion, since it is impossible for Us to guarantee, predict or provide for the behaviour of Your system.</li>
                <li>We may use third party cookies to track user behaviour and to improve the quality of Our services. However, such cookies shall not store any kind of personal information, nor shall such information be disclosed to any third party.</li>
                <li>You have the option to either accept or refuse these cookies, and will be informed when a cookie is being sent to Your computer. If You choose to refuse Our cookies, You may not be able to use some portions of Our Service.</li>
                <li>The information We collect with cookies is not sold, rented, or shared with any third parties.</li>
            </ul>
            <p>6. <b>SERVICE PROVIDERS</b></p>
            <ul>
                <li>We may employ third-party companies and individuals for to the following reasons:
                    <ol>
                        <li>To facilitate Our Service;</li>
                        <li>To provide the Service on Our behalf;</li>
                        <li>To perform Service-related tasks; or</li>
                        <li>To assist Us in analyzing how Our Service is used.</li>
                    </ol>
                </li>
                <li>We will inform You when these third-party providers have access to Your Personal Information in order to perform tasks assigned to them on Our behalf. They are contractually mandated not to disclose or use the information for any other purpose.</li>
            </ul>
            <p>7. <b>INFORMATION RETENTION</b></p>
            <ul>
                <li>On receiving a request to delete any information you have shared with us, the Organization will archive all Personal Information. Archived information will be retained by the Organization for a period of 3 months in its secure database for the purpose of our records. Your non-personally identifiable information is retained for a period of 3 months.</li>
            </ul>
            <p>8. <b>SECURITY PROCEDURES</b></p>
            <ul>
                <li>We have implemented commercially acceptable security policies, rules and technical measures as required under Section 8 of the SPI rules, to protect any kind of Personal Information that We have under Our control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss. However, it is contended that no method of transmission over the Internet, or method of electronic storage, is 100% secure. Thus, while We strive to protect Your personal data, the Organization cannot ensure and does not warrant the absolute security of any information You transmit to Us.</li>
            </ul>
            <p>9. <b>OPTING OUT OF MARKETING COMMUNICATION</b></p>
            <ul>
                <li>If You wish to opt-out of receiving any marketing communication from us, You can write to us at contactus@catalysts.org stating the same and we shall comply with such request.</li>
            </ul>
            <p>10. <b>THIRD-PARTY LINKS</b></p>
            <ul>
                <li>Our Service may contain links to other websites (“Linked Sites”). The Linked Sites are not operated by Us. We strongly advise You to review the Privacy Policy of these websites as We are not responsible for the content of any Linked Site, including, without limitation to, any link contained in a Linked Site, or any changes or updates to a Linked Site.</li>
                <li>Our Organization does not intend the Linked Sites to be referrals to, endorsements of, or affiliation with the primary Website.</li>
                <li>On accessing the Linked Sites, you shall be governed by the terms of use, privacy policy and such other additional policies of the Linked Sites. You further acknowledge and agree that Our Organization shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, advertising, products, services or other materials available on or through any Linked Sites or for any errors, defamatory content, libel, slander, omissions, falsehoods, obscene content, pornographic material, or any profanity contained therein.</li>
            </ul>
            <p>11. <b>GOVERNING LAW AND JURISDICTION</b></p>
            <ul>
                <li>This Privacy Policy shall be governed by and constructed in accordance with the Applicable Laws of India without reference to conflict of laws principles. The courts in Bangalore, India shall have the exclusive jurisdiction to determine any disputes arising in relation to, or under this Privacy Policy.</li>
            </ul>
            <p>12. <b>GRIEVANCES</b></p>
            <ul>
                <li>If You have any grievances as to the usage of any of Your Personal Information or any other privacy concerns, you can contact the Grievance Officer whose details are provided hereunder:</li>
            </ul>
            <p><b>E-mail Address:</b> <Link href={'mailto:contactus@catalysts.org'}>contactus@catalysts.org</Link></p>
        </Container>
        <Footer />
        <Copyright />
        </>
    );
}